name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # you can trigger the workflow manually

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Old code. Saving just in case it is needed
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Removing to see if this addresses an issue with the Tensorflow distribution
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # May need to use this, but I think the above "Set up Docker Buildx does the same thing"
    # - name: Use buildx
    #   run: docker buildx create --use

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build the Docker image
      run: docker buildx build . --push --file Dockerfile --platform linux/amd64,linux/arm64 --tag ${{ secrets.DOCKER_USERNAME }}/machine-learning-general-purpose
